# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/kafkalainen/Documents/unreal_engine/5.3.2-downloaded/Linux_Unreal_Engine_5.3.2
GAMEPROJECTFILE =/home/kafkalainen/Documents/ue_projects/testProject/testProject.uproject

TARGETS = \
	testProject-Linux-DebugGame  \
	testProject-Linux-Shipping  \
	testProject \
	testProjectEditor-Linux-DebugGame  \
	testProjectEditor-Linux-Shipping  \
	testProjectEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend testProjectEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug testProjectEditor-Linux-Debug


testProject-Linux-DebugGame:
	 $(PROJECTBUILD) testProject Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

testProject-Linux-Shipping:
	 $(PROJECTBUILD) testProject Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

testProject:
	 $(PROJECTBUILD) testProject Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

testProjectEditor-Linux-DebugGame:
	 $(PROJECTBUILD) testProjectEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

testProjectEditor-Linux-Shipping:
	 $(PROJECTBUILD) testProjectEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

testProjectEditor:
	 $(PROJECTBUILD) testProjectEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
